// templates/frontend/react/levels/level_2/files/mobile/src/App.tsx
import React, { useState } from "react";

type Screen = "home" | "todos";

export default function App() {
  const [screen, setScreen] = useState<Screen>("home");
  return <main><h1>Reverse Vibe Coding</h1><nav><button onClick={() => setScreen("home")}>Home</button><button onClick={() => setScreen("todos")}>Todos</button></nav>{screen === "home" ? <p>Choose a project screen.</p> : <p>Todo screen placeholder.</p>}</main>;
}

// templates/frontend/vue/levels/level_2/files/mobile/src/App.vue
<template>
  <main><h1>Reverse Vibe Coding</h1><nav><button @click="screen = 'home'">Home</button><button @click="screen = 'todos'">Todos</button></nav><p v-if="screen === 'home'">Choose a project screen.</p><p v-else>Todo screen placeholder.</p></main>
</template>
<script setup lang="ts">
import { ref } from "vue";
const screen = ref<"home" | "todos">("home");
</script>
